import type { NodeTrace } from '@/core/traces/types';

export const DEMO_TRACES: NodeTrace[] = [
  {
    id: 'trace-hermes-aag-workspace',
    title: 'Hermes -> AAG -> Workspace',
    subtitle: 'A controlled Google Workspace action with approval and audit',
    status: 'needs_approval',
    startedAt: '2026-06-14T09:12:00Z',
    events: [
      {
        id: 'workspace-1',
        runId: 'workspace-run',
        source: 'hermes',
        eventType: 'run.started',
        actor: 'hermes',
        status: 'running',
        timestamp: '2026-06-14T09:12:00Z',
        summary: 'Hermes receives a workspace task',
        detail: 'Hermes starts a user-requested workflow that will touch Calendar, Docs, and Drive.',
      },
      {
        id: 'workspace-2',
        parentEventId: 'workspace-1',
        runId: 'workspace-run',
        source: 'hermes',
        eventType: 'agent.plan',
        actor: 'hermes',
        status: 'running',
        timestamp: '2026-06-14T09:12:05Z',
        summary: 'Plan bundle before side effects',
        detail: 'Hermes groups the intended Workspace changes and keeps execution behind AAG.',
      },
      {
        id: 'workspace-3',
        parentEventId: 'workspace-2',
        runId: 'workspace-run',
        source: 'aag',
        eventType: 'aag.decision',
        actor: 'aag',
        tool: 'google.workspace.bundle',
        decision: 'require_approval',
        risk: 'medium',
        status: 'needs_approval',
        timestamp: '2026-06-14T09:12:11Z',
        summary: 'AAG requires approval',
        detail: 'AAG records a redacted action bundle, computes payload hashes, and queues operator approval.',
        redactedPayloadHash: 'sha256:redacted-workspace-bundle',
      },
      {
        id: 'workspace-4',
        parentEventId: 'workspace-3',
        runId: 'workspace-run',
        source: 'aag',
        eventType: 'approval.required',
        actor: 'operator',
        tool: 'google.workspace.bundle',
        decision: 'pending',
        risk: 'medium',
        status: 'needs_approval',
        timestamp: '2026-06-14T09:12:13Z',
        summary: 'Operator approval is pending',
        detail: 'The action is visible in the approval queue. No provider mutation happens before approval.',
      },
    ],
  },
  {
    id: 'trace-openclaw-worker',
    title: 'Hermes -> OpenClaw Worker',
    subtitle: 'Delegated browser/operator work through the MCP boundary',
    status: 'succeeded',
    startedAt: '2026-06-14T10:30:00Z',
    events: [
      {
        id: 'openclaw-1',
        runId: 'openclaw-run',
        source: 'hermes',
        eventType: 'run.started',
        actor: 'hermes',
        status: 'running',
        timestamp: '2026-06-14T10:30:00Z',
        summary: 'Hermes delegates bounded work',
        detail: 'Hermes starts a worker task instead of taking direct shell or browser control.',
      },
      {
        id: 'openclaw-2',
        parentEventId: 'openclaw-1',
        runId: 'openclaw-run',
        source: 'hermes',
        eventType: 'tool.requested',
        actor: 'hermes',
        tool: 'openclaw_worker.start_task',
        status: 'running',
        timestamp: '2026-06-14T10:30:04Z',
        summary: 'Call OpenClaw worker MCP',
        detail: 'The MCP adapter creates a job id and routes the request to OpenClaw through the local gateway.',
      },
      {
        id: 'openclaw-3',
        parentEventId: 'openclaw-2',
        runId: 'openclaw-run',
        source: 'openclaw',
        eventType: 'worker.started',
        actor: 'openclaw/default',
        status: 'running',
        timestamp: '2026-06-14T10:30:06Z',
        summary: 'OpenClaw worker starts',
        detail: 'The worker runs behind the gateway with concurrency held at one to avoid sandbox conflicts.',
      },
      {
        id: 'openclaw-4',
        parentEventId: 'openclaw-3',
        runId: 'openclaw-run',
        source: 'openclaw',
        eventType: 'worker.completed',
        actor: 'openclaw/default',
        status: 'succeeded',
        timestamp: '2026-06-14T10:31:21Z',
        summary: 'Worker returns result',
        detail: 'OpenClaw returns a bounded answer to Hermes. The worker state stays isolated from Hermes.',
      },
      {
        id: 'openclaw-5',
        parentEventId: 'openclaw-4',
        runId: 'openclaw-run',
        source: 'hermes',
        eventType: 'run.completed',
        actor: 'hermes',
        status: 'succeeded',
        timestamp: '2026-06-14T10:31:33Z',
        summary: 'Hermes completes the run',
        detail: 'Hermes reports the result to the user after the delegated worker task finishes.',
      },
    ],
  },
  {
    id: 'trace-sentinel-recovery',
    title: 'Sentinel detects and recovers',
    subtitle: 'Health drift becomes visible instead of silently failing',
    status: 'recovered',
    startedAt: '2026-06-14T11:45:00Z',
    events: [
      {
        id: 'sentinel-1',
        runId: 'sentinel-run',
        source: 'sentinel',
        eventType: 'health.check',
        actor: 'openclaw-worker-sentinel',
        status: 'running',
        timestamp: '2026-06-14T11:45:00Z',
        summary: 'Sentinel runs health check',
        detail: 'The sentinel probes the OpenClaw worker path through a cheap local health check.',
      },
      {
        id: 'sentinel-2',
        parentEventId: 'sentinel-1',
        runId: 'sentinel-run',
        source: 'sentinel',
        eventType: 'sentinel.alert',
        actor: 'openclaw-worker-sentinel',
        status: 'failed',
        timestamp: '2026-06-14T11:45:03Z',
        summary: 'Worker path reports broken',
        detail: 'The sentinel records a transition to broken and emits an operator-visible alert without printing secrets.',
      },
      {
        id: 'sentinel-3',
        parentEventId: 'sentinel-2',
        runId: 'sentinel-run',
        source: 'sentinel',
        eventType: 'sentinel.recovery',
        actor: 'openclaw-worker-sentinel',
        status: 'recovered',
        timestamp: '2026-06-14T11:57:42Z',
        summary: 'Worker path recovers',
        detail: 'A later check sees the worker path return to ok and records the recovery transition.',
      },
    ],
  },
];

export function getDemoTrace(id: string): NodeTrace | undefined {
  return DEMO_TRACES.find((trace) => trace.id === id);
}
